# Generated by Django 3.2.8 on 2021-10-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=207)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('adanger', 'Prioritu High'), ('bwarning', 'Priority Medium'), ('csuccess', 'Priority Low')], default=('adanger', 'Prioritu High'), max_length=30)),
                ('complete', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.username')),
            ],
        ),
    ]
